import AuthenticatedLayout from '@/Layouts/AuthenticatedLayout';
import { Head } from '@inertiajs/react';
import Badge from '@/Components/Badge';
import SecondaryButton from '@/Components/SecondaryButton';

const MONTHS = ['', 'January', 'February', 'March', 'April', 'May', 'June', 'July', 'August', 'September', 'October', 'November', 'December'];

function Row({ label, value, strong }) {
    return (
        <div className="flex items-center justify-between py-2">
            <span className={strong ? 'font-semibold text-slate-800' : 'text-slate-500'}>{label}</span>
            <span className={strong ? 'font-semibold text-slate-800' : 'text-slate-700'}>
                {Number(value).toLocaleString(undefined, { minimumFractionDigits: 2 })}
            </span>
        </div>
    );
}

export default function Payslip({ payroll }) {
    const emp = payroll.employee;

    return (
        <AuthenticatedLayout header="Payslip">
            <Head title={`Payslip — ${MONTHS[payroll.period_month]} ${payroll.period_year}`} />

            <div className="mx-auto max-w-xl rounded-xl border border-slate-200 bg-white p-8 print:border-none">
                <div className="flex items-start justify-between border-b border-slate-100 pb-4">
                    <div>
                        <h2 className="text-lg font-semibold text-slate-800">Payslip</h2>
                        <p className="text-sm text-slate-500">{MONTHS[payroll.period_month]} {payroll.period_year}</p>
                    </div>
                    <Badge status={payroll.status} />
                </div>

                <div className="mt-4 grid grid-cols-2 gap-3 border-b border-slate-100 pb-4 text-sm">
                    <div>
                        <p className="text-xs text-slate-400">Employee</p>
                        <p className="text-slate-700">{emp.user.name}</p>
                    </div>
                    <div>
                        <p className="text-xs text-slate-400">Employee number</p>
                        <p className="text-slate-700">{emp.employee_number}</p>
                    </div>
                    <div>
                        <p className="text-xs text-slate-400">Department</p>
                        <p className="text-slate-700">{emp.department?.name ?? '—'}</p>
                    </div>
                    <div>
                        <p className="text-xs text-slate-400">Position</p>
                        <p className="text-slate-700">{emp.position?.title ?? '—'}</p>
                    </div>
                </div>

                <div className="mt-4 divide-y divide-slate-100 text-sm">
                    <Row label="Basic salary" value={payroll.basic_salary} />
                    <Row label="Allowances" value={payroll.allowances} />
                    <Row label="Overtime pay" value={payroll.overtime_pay} />
                    <Row label="Deductions" value={-payroll.deductions} />
                    <Row label={`Leave / absence deductions (${payroll.days_absent} day(s))`} value={-payroll.leave_deductions} />
                    <Row label="Net salary" value={payroll.net_salary} strong />
                </div>

                <p className="mt-4 text-xs text-slate-400">
                    Days present: {payroll.days_present} · Days absent: {payroll.days_absent}
                    {payroll.generated_by?.name && <> · Generated by {payroll.generated_by.name}</>}
                </p>

                <SecondaryButton onClick={() => window.print()} className="mt-6 print:hidden">Print payslip</SecondaryButton>
            </div>
        </AuthenticatedLayout>
    );
}
